# Generated by Django 4.0.3 on 2023-03-07 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_alter_salesrecord_automobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='automobile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_record', to='sales_rest.automobilevo'),
        ),
    ]
