# Generated by Django 4.0.3 on 2023-03-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_salesperson_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='manufacturer',
            field=models.CharField(default=2012, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='model',
            field=models.CharField(default='Sebring', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='year',
            field=models.PositiveSmallIntegerField(default=2012),
            preserve_default=False,
        ),
    ]
