# Generated by Django 4.0.3 on 2023-03-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_appointment_automobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appt_date_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appt_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appt_time',
            field=models.TimeField(null=True),
        ),
    ]
