# Generated by Django 4.0.3 on 2023-03-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_remove_appointment_appt_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='employee_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
