# Generated by Django 4.0.3 on 2023-03-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='vin',
        ),
    ]
