# Generated by Django 4.0.3 on 2023-03-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_remove_appointment_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='owner',
            new_name='customer_name',
        ),
    ]
