# Generated by Django 4.0.3 on 2023-03-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_appointment_isvip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='isVip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
