# Generated by Django 4.0.3 on 2023-03-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0012_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('customer_name',)},
        ),
        migrations.AlterModelOptions(
            name='automobilevo',
            options={'ordering': ('vin',), 'verbose_name_plural': 'Automobile VOs'},
        ),
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ('name',)},
        ),
    ]
