# Generated by Django 4.0.3 on 2023-03-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0013_alter_appointment_options_alter_automobilevo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('appt_date',)},
        ),
    ]
